//! Transparency query handler — responds to user queries about last inference.
//!
//! Handles `TransparencyQuery::InferenceExplanation` by returning context from
//! the most recent inference cycle: request description, response text, working memory,
//! and number of reasoning rounds.

use bus::events::memory::MemoryChunk;
use bus::events::transparency::InferenceExplanationResponse;

/// Internal state captured after each successful inference cycle.
#[derive(Debug, Clone)]
pub(crate) struct InferenceState {
    /// Description of the request/query (NOT raw prompt text).
    pub request_context: String,
    /// The response text generated by the inference.
    pub response_text: String,
    /// Working memory chunks that were in context during inference.
    pub working_memory_context: Vec<MemoryChunk>,
    /// Number of reasoning rounds executed.
    pub rounds_completed: usize,
}

impl InferenceState {
    /// Convert this state into a transparency response.
    pub fn to_response(&self) -> InferenceExplanationResponse {
        InferenceExplanationResponse {
            request_context: self.request_context.clone(),
            response_text: self.response_text.clone(),
            working_memory_context: self.working_memory_context.clone(),
            rounds_completed: self.rounds_completed,
        }
    }
}

/// Handle inference transparency query: construct and return last inference explanation.
///
/// If no inference has been completed yet, returns a response with placeholder text.
pub async fn handle_transparency_query(
    last_state: &Option<InferenceState>,
) -> InferenceExplanationResponse {
    match last_state {
        Some(state) => state.to_response(),
        None => InferenceExplanationResponse {
            request_context: "No inference cycle completed yet".to_string(),
            response_text: "No inference cycle completed yet".to_string(),
            working_memory_context: vec![],
            rounds_completed: 0,
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::SystemTime;

    #[test]
    fn inference_state_converts_to_response() {
        let state = InferenceState {
            request_context: "User asked about debugging".to_string(),
            response_text: "Here's how to debug...".to_string(),
            working_memory_context: vec![MemoryChunk {
                text: "User prefers Rust".to_string(),
                score: 0.95,
                timestamp: SystemTime::now(),
            }],
            rounds_completed: 2,
        };

        let response = state.to_response();
        assert_eq!(response.request_context, "User asked about debugging");
        assert_eq!(response.response_text, "Here's how to debug...");
        assert_eq!(response.rounds_completed, 2);
        assert_eq!(response.working_memory_context.len(), 1);
    }

    #[tokio::test]
    async fn handle_transparency_query_with_no_state() {
        let response = handle_transparency_query(&None).await;
        assert_eq!(response.request_context, "No inference cycle completed yet");
        assert_eq!(response.response_text, "No inference cycle completed yet");
        assert_eq!(response.rounds_completed, 0);
        assert!(response.working_memory_context.is_empty());
    }

    #[tokio::test]
    async fn handle_transparency_query_with_state() {
        let state = InferenceState {
            request_context: "Test query".to_string(),
            response_text: "Test response".to_string(),
            working_memory_context: vec![],
            rounds_completed: 1,
        };

        let response = handle_transparency_query(&Some(state)).await;
        assert_eq!(response.request_context, "Test query");
        assert_eq!(response.response_text, "Test response");
        assert_eq!(response.rounds_completed, 1);
    }
}
